### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by AdminRAT** [discordconsole-team/DiscordConsole#40]
When downloading the 2.4.0 from the releases page, I get 2.3.9 instead...

```DiscordConsole 2.3.9

DiscordConsole  Copyright (C) 2017  LEGOlord208
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions.

Loading language...
Checking for updates... 
Update available! Version 2.4.0
Download from https://github.com/discordconsole-team/DiscordConsole/releases/tag/2.4.0
Reading bookmarks...

Please paste your 'token' here.
User tokens are prefixed with 'user '
Webhook tokens are prefixed with 'webhook ', and their URL or id/token
>

**Comment by Mnpn03** [comment]
Since LEGOlord208 is the copyright holder you are running an older version of DiscordConsole, the version is always printed before the copyright notice. 2.4.0 is available at https://github.com/discordconsole-team/DiscordConsole/releases/tag/2.4.0.

**Comment by Mnpn03** [comment]
Just checked, Linux distribution is 2.4.0, but the Windows version uploaded was indeed 2.3.9. I will update the binaries right away. Thanks for letting me know!

**Comment by AdminRAT** [comment]
I noticed the Windows binaries as well... maybe those didn't update too?

**Comment by Mnpn03** [comment]
^ The issue was compiling the 2.4.0 binaries, as it seems like the Windows version compiled was 2.3.9.

**Comment by Mnpn03** [comment]
Issue resolved. I messed up trying to compile.
Quoting jD91mZM2 in our DiscordConsole Support server:
`turns out he was compiling an outdated separate copy in the project in the right location while his updated version was in the wrong location`

My bad.
New and updated executables will be uploaded as part of 2.4.1.
