### ISSUE TITLE
Run golint and go vet

### ISSUE THREAD

**Issue by jD91mZM2** [discordconsole-team/DiscordConsole#42]
Travis is broken becuase `go vet` returns a non-zero exit status. This is because there is an issue you haven't resolved.
Also, there are also a couple of [golint](https://github.com/golang/lint) issues. Fix those.

**Comment by Mnpn03** [comment]
~~pessimist~~

on my to-do list, thanks.

**Comment by Mnpn03** [comment]
Resolved in commit ce82fc8 and 3f8a8ac.
Thanks!
