### ISSUE TITLE
I was just trying to log in 

### ISSUE THREAD

**Issue by NightmareOkami** [discordconsole-team/DiscordConsole#49]
Http 401 unauthorized 
![IMG_20201219_015120](https://user-images.githubusercontent.com/73287388/102684276-c32ad580-419c-11eb-80d6-8a19e6dd6652.jpg)

**Comment by Mnpn03** [comment]
Your token is probably incorrect. Double check whether or not you need to prefix it with `user `, too.

**Comment by NightmareOkami** [comment]
It insta crashes now if i type anything

**Comment by Mnpn03** [comment]
If you're still stuck on the token screen, you have to enter it as `user <token_here>` if it's a user token or just `<token_here>` if it's a bot token. The program will automatically close with that unauthorised error if the token is incorrect or is not prefixed correctly.
